apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: technicaltest-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: technicaltest-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50